server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/blackjack
    username: root
    password: 78446660579
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  
  sql:
    init:
      mode: embedded
      continue-on-error: true
      platform: mysql
      schema-locations: classpath:schema.sql
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blackjack
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
  packages-to-scan: com.blackjack.controller
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.boot.autoconfigure.sql: DEBUG
    com.blackjack: DEBUG 